coverage_service: cobertura_xml
xcodeproj: platforms/ios/example/Wysiwyg.xcodeproj
scheme: Wysiwyg
output_directory: platforms/ios/lib/coverage
build_directory: platforms/ios/example/DerivedData
ignore:
  - platforms/ios/example/**
  - platforms/ios/lib/WysiwygComposer/Tests/**
  - platforms/ios/lib/WysiwygComposer/Sources/WysiwygComposer/WysiwygComposer.swift